'use client'
import Header from './Components/Header'
import Footer from './Components/Footer'

import { ChakraProvider } from "@chakra-ui/react"

 export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
 }

 export default function RootLayout({
   children,
 }: {
   children: React.ReactNode
 }) {
   return (
     <html lang="en">
      <body>
        <ChakraProvider>
          <Header />
          {children}
          <Footer />
        </ChakraProvider>
      </body>
     </html>  
    )
}
